### ISSUE TITLE
Fix unit test error in windows and MAC

### ISSUE THREAD

**Issue by Miachol** [JhuangLab/BioInstaller#3]
- [x] Error: initial (@test_install_uilts.R#40) 
- [x] Failure: is.biosoftwares.db.active (@test_active.R#10) 
- [x] Failure: set.makedir (@test_install_uilts.R#60) 
- [x] Failure: set.makedir (@test_install_uilts.R#63) 
- [x] Failure: set.makedir (@test_install_uilts.R#65)

**Comment by Miachol** [comment]
fix all CRAN unittest error (commit:aafff0c)
